### ISSUE TITLE
Feature request: Option to toggle thermostat from the temperature view button

### ISSUE THREAD

**Issue by PalminX** [aperezm85/streamdeck-tado-plugin#4]
Currently, there are two streamdeck button types: one which shows the current temperature of a thermostat, and one which can be used to toggle a thermostat on/off. 

Since the temperature display does not have a "keypress" function, I think it would be good if the two could be merged, i.e. have a button which shows the current temp of a thermostat, and have it toggle heating on/off by keypress (which could be visualized by changing the temp icon).

**Comment by aperezm85** [comment]
Updated with version 2.
Thanks for the recommendation!

**Comment by PalminX** [comment]
@aperezm85 When/how will this update be available in the official Stream Deck plugins?

**Comment by aperezm85** [comment]
Hi. Not sure, I uploaded yesterday, they usually take a couple of days…

I’ll let you know !

**Comment by aperezm85** [comment]
It was confirmed by elgato that the plug-in was updated. It should update
automatically.

Thanks
